PR_4
ipcross/react-blog pull request #4
Opened 2017-07-03 14:30 UTC by ipcross

2017-07-05 09:37 UTC, blackleadsu requested changes
1. нужно исправить ошибки линтера
`./node_modules/eslint/bin/eslint.js  ./src --ext js,jsx`
2. в PieChart не импортировал ReactDOM и c3. c3 не подключил в package.json.
3. url у картинок всё-таки стоит настоящие сделать) 
4. имеет смысл разделить на подпапки содержимое `components/ui`. 
5. см. правку по работе hotReload (assets вместо dist)

2017-07-05 09:37 UTC, blackleaden commented on index.html
> +    <script src="dist/bundle.js"></script>
Для корректной работы hotReload здесь следует указать asset вместо dist, так как именно этот путь указан в конфиге вебпака (publicPath)

2017-07-06 09:46 UTC, blackleadsu requested changes
С хот-релоадом всё ок, но линтер до сих пор выдает ошибки и warning'и. Комментами я показал пару мест, где исправить. Остальные сообщения тоже нужно устранить.

2017-07-06 09:46 UTC, blackleaden commented on src/components/ui/BlogList.jsx
>  import BlogItem from '../ui/BlogItem';
Линтер правильно ругается - как минимум `./BlogItem`, а еще лучше -- использовать абсолютные пути по проекту, в данном случае `componetns/ui/BlogItem`.

2017-07-06 09:46 UTC, blackleaden commented on src/components/ui/PieChart.jsx
> +import ReactDOM from 'react-dom';
и `import c3 from 'c3';`

2017-07-06 09:46 UTC, blackleaden commented on index.html
>      <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.13/c3.min.js"></script>
скрипты с cloudflare не нужны, c3 просто подключается в PieChart.js

2017-07-07 11:47 UTC, blackleadsu requested changes

2017-07-07 11:47 UTC, blackleaden commented on .eslintrc.js
> +  "settings": {
Нашел. Нужно расширить этот пункт конфига, чтобы линтер мог разрешать пути к jsx (проблема была в этом):
```
"settings": {
    "import/extensions": [ '.js', '.jsx'],
    "import/resolver": {
      "node": {
        'extensions': [
          '.js',
          '.jsx'
        ],
        "moduleDirectory": [
          "node_modules",
          "src"
        ]
      }
    }
  }
```
После этой правки остается два warning'а и можно переходить к следующему заданию!

2017-07-07 12:02 UTC, ipcross commented on .eslintrc.js
> +  "settings": {
Это не помогает.

2017-07-08 07:52 UTC, merged